$axure.loadCurrentPage({
  "url":"crash-report.html",
  "generationDate":new Date(1459858381499.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9b4571a56fc942529734a1dedd83e3a2",
    "type":"Axure:Page",
    "name":"Crash-report",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"155b409bc36b4be5a149bf86fc6c8415",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":10},
            "size":{
              "width":215,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9ae881708e9467c951ec10b48b0f220",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18,
                  "y":10},
                "size":{
                  "width":215,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e9d69c977cb4824947b01ece6dc9479",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":292,
              "y":8},
            "size":{
              "width":28,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab8d3fb14e264afba35f02ed029552f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":292,
                  "y":8},
                "size":{
                  "width":28,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"5edf1ac33f53438784f5366e94544fab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":319,
              "y":3},
            "size":{
              "width":16,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e84c42d6c37148e8a2b238c62f64e23a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":319,
                  "y":3},
                "size":{
                  "width":16,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe012745d9b243f387d9d253e98af92e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":8},
            "size":{
              "width":28,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69575a0685104851a1435ffce6f7bec4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":401,
                  "y":8},
                "size":{
                  "width":28,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"1a39c236a3f8402689bff527f043bb66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":428,
              "y":3},
            "size":{
              "width":16,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e001e58e2904b6bb066cb2bd82bf0f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":428,
                  "y":3},
                "size":{
                  "width":16,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bee519bebefc4878aa9cda539d4acbdb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":345,
              "y":8},
            "size":{
              "width":28,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"461335744daa41d29aaacf5b2c711767",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":345,
                  "y":8},
                "size":{
                  "width":28,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"633b2727eb934fe6b05efefc4865e2a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":372,
              "y":3},
            "size":{
              "width":16,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"585d524759994a08b375e8e8ff53d8c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":372,
                  "y":3},
                "size":{
                  "width":16,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa442d7598484acc98d1bfdfdbece9c3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":506,
              "y":5},
            "size":{
              "width":21,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b9e47c459594ffca636c2bfa2dfabd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":506,
                  "y":5},
                "size":{
                  "width":21,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u14.png"}},
{
          "id":"ecd885a466e442c3819794a3fb14639d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":533,
              "y":0},
            "size":{
              "width":16,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f6baea1fa7045fbb0053c0f7f49856c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":533,
                  "y":0},
                "size":{
                  "width":16,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afff529b7d9a46fd94e5f6846b31d48c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":453,
              "y":7},
            "size":{
              "width":24,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5eca1f5903664e2e83759aa17129625b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":453,
                  "y":7},
                "size":{
                  "width":24,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u18.png"}},
{
          "id":"142985acb1804726bb51a7dd5864dd1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":480,
              "y":2},
            "size":{
              "width":16,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de710c2246d54deeaa64b98e85722835",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":480,
                  "y":2},
                "size":{
                  "width":16,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e349382d9d64455a7e43cba1bdd49d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":554,
              "y":8},
            "size":{
              "width":28,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d711f13d2f68438abe77a90b11ef9f55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":554,
                  "y":8},
                "size":{
                  "width":28,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u47.png"}},
{
          "id":"4ee8f6b9e6504be8bbc9a0155a5e8756",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":581,
              "y":3},
            "size":{
              "width":16,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"450edbcb46e74ff0a8c77d2ede7cccd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":581,
                  "y":3},
                "size":{
                  "width":16,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e77b85ff5b8f4a43b3c45b2cda060152",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":0},
            "size":{
              "width":10,
              "height":540}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/crash-report/u26_line.png"}},
{
          "id":"da898d4cf5b543d1aa307472309e0661",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":286,
              "y":31},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de2dca42095c4e5a97fa6c86267b190b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":286,
                  "y":31},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"973c7639fdb746059b7a27c5c5b237b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":344,
              "y":31},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83d43609765c48ada380415ef1326ca9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":344,
                  "y":31},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"448e5517e9f942179c4ade5a830ed756",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":401,
              "y":31},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"addd54ed6ae54d0790511b4a77e7e551",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":401,
                  "y":31},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f040462e21cf4003a26560bbeccc3d84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":553,
              "y":32},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ce8df5852354237bfc27e76d92f3296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":553,
                  "y":32},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1ae5fb495e04bfca265c6a29226e0c6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":530},
            "size":{
              "width":690,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/crash-report/u35_line.png"}},
{
          "id":"67ea8859c62040bea71516bd80a23741",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":500},
            "size":{
              "width":690,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/crash-report/u35_line.png"}},
{
          "id":"5c3fc36076aa4dabb164caf442a45ad9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":680,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/crash-report/u37_line.png"}},
{
          "id":"7427cf2c7ac142668a16f9b9e3ad1a0c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":11,
              "y":505},
            "size":{
              "width":54,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"005e47670508420a9803e24f7a965e88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":11,
                  "y":505},
                "size":{
                  "width":54,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u32.png"}},
{
          "id":"b93375b087df46998565722ca4d8e01c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":68,
              "y":515},
            "size":{
              "width":28,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bdcc4db465947e0b16f877c86a0690c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":68,
                  "y":515},
                "size":{
                  "width":28,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10dcd1a3445a4f469a1b684127182a2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":8},
            "size":{
              "width":160,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"912bdc71d3df4154bebb744e79c0bb5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":750,
                  "y":8},
                "size":{
                  "width":160,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d08b1f0846f14c1396215f1ab29962da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":614,
              "y":8},
            "size":{
              "width":30,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d99a88480eb24be88b45567e8970fb34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":614,
                  "y":8},
                "size":{
                  "width":30,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u38.jpg"}},
{
          "id":"17ad60574f2245489d274f271e88d47e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":646,
              "y":8},
            "size":{
              "width":52,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdac54d781004c04a4564d8c6f327547",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":646,
                  "y":8},
                "size":{
                  "width":52,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"436039ca777345e194bf325fe8db2931",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":514},
            "size":{
              "width":535,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73b1f7451bf545c091a8c3b8294e59f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":514},
                "size":{
                  "width":535,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efac9e425db9418db8be04aa4d41c7e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":165,
              "y":108},
            "size":{
              "width":349,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"886923b7999048d28c20580f28a04db4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":165,
                  "y":108},
                "size":{
                  "width":349,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef77795cc196408cbfd95158ee528c4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":165,
              "y":203},
            "size":{
              "width":349,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d9526f302da4ac8b4d27a78bc454b52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":165,
                  "y":203},
                "size":{
                  "width":349,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b240984edddb480aaec40435a0b02a32",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":148},
            "size":{
              "width":155,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9510dd8e6374426fb852eff176a1f36a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":148},
                "size":{
                  "width":155,
                  "height":15}},
              "adaptiveStyles":{
}}]},
{
          "id":"016ff16f5ab94295904a63873d98c8a1",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":173},
            "size":{
              "width":155,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9c907d1b6d24e1e887114dac7eca173",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":173},
                "size":{
                  "width":155,
                  "height":15}},
              "adaptiveStyles":{
}}]},
{
          "id":"2d1fc7b9b5964044bcb7ed1325bf2a6f",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":230},
            "size":{
              "width":385,
              "height":150}},
          "adaptiveStyles":{
}},
{
          "id":"aee3829b2ded49a893af764c01a3f70c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":410},
            "size":{
              "width":113,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee466a4ef35e4c00bacba70a2fa22ef0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":410},
                "size":{
                  "width":113,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "155b409bc36b4be5a149bf86fc6c8415":{
      "scriptId":"u0"},
    "a9ae881708e9467c951ec10b48b0f220":{
      "scriptId":"u1"},
    "6e9d69c977cb4824947b01ece6dc9479":{
      "scriptId":"u2"},
    "ab8d3fb14e264afba35f02ed029552f3":{
      "scriptId":"u3"},
    "5edf1ac33f53438784f5366e94544fab":{
      "scriptId":"u4"},
    "e84c42d6c37148e8a2b238c62f64e23a":{
      "scriptId":"u5"},
    "fe012745d9b243f387d9d253e98af92e":{
      "scriptId":"u6"},
    "69575a0685104851a1435ffce6f7bec4":{
      "scriptId":"u7"},
    "1a39c236a3f8402689bff527f043bb66":{
      "scriptId":"u8"},
    "1e001e58e2904b6bb066cb2bd82bf0f6":{
      "scriptId":"u9"},
    "bee519bebefc4878aa9cda539d4acbdb":{
      "scriptId":"u10"},
    "461335744daa41d29aaacf5b2c711767":{
      "scriptId":"u11"},
    "633b2727eb934fe6b05efefc4865e2a5":{
      "scriptId":"u12"},
    "585d524759994a08b375e8e8ff53d8c0":{
      "scriptId":"u13"},
    "aa442d7598484acc98d1bfdfdbece9c3":{
      "scriptId":"u14"},
    "7b9e47c459594ffca636c2bfa2dfabd1":{
      "scriptId":"u15"},
    "ecd885a466e442c3819794a3fb14639d":{
      "scriptId":"u16"},
    "5f6baea1fa7045fbb0053c0f7f49856c":{
      "scriptId":"u17"},
    "afff529b7d9a46fd94e5f6846b31d48c":{
      "scriptId":"u18"},
    "5eca1f5903664e2e83759aa17129625b":{
      "scriptId":"u19"},
    "142985acb1804726bb51a7dd5864dd1f":{
      "scriptId":"u20"},
    "de710c2246d54deeaa64b98e85722835":{
      "scriptId":"u21"},
    "2e349382d9d64455a7e43cba1bdd49d2":{
      "scriptId":"u22"},
    "d711f13d2f68438abe77a90b11ef9f55":{
      "scriptId":"u23"},
    "4ee8f6b9e6504be8bbc9a0155a5e8756":{
      "scriptId":"u24"},
    "450edbcb46e74ff0a8c77d2ede7cccd8":{
      "scriptId":"u25"},
    "e77b85ff5b8f4a43b3c45b2cda060152":{
      "scriptId":"u26"},
    "da898d4cf5b543d1aa307472309e0661":{
      "scriptId":"u27"},
    "de2dca42095c4e5a97fa6c86267b190b":{
      "scriptId":"u28"},
    "973c7639fdb746059b7a27c5c5b237b0":{
      "scriptId":"u29"},
    "83d43609765c48ada380415ef1326ca9":{
      "scriptId":"u30"},
    "448e5517e9f942179c4ade5a830ed756":{
      "scriptId":"u31"},
    "addd54ed6ae54d0790511b4a77e7e551":{
      "scriptId":"u32"},
    "f040462e21cf4003a26560bbeccc3d84":{
      "scriptId":"u33"},
    "2ce8df5852354237bfc27e76d92f3296":{
      "scriptId":"u34"},
    "c1ae5fb495e04bfca265c6a29226e0c6":{
      "scriptId":"u35"},
    "67ea8859c62040bea71516bd80a23741":{
      "scriptId":"u36"},
    "5c3fc36076aa4dabb164caf442a45ad9":{
      "scriptId":"u37"},
    "7427cf2c7ac142668a16f9b9e3ad1a0c":{
      "scriptId":"u38"},
    "005e47670508420a9803e24f7a965e88":{
      "scriptId":"u39"},
    "b93375b087df46998565722ca4d8e01c":{
      "scriptId":"u40"},
    "3bdcc4db465947e0b16f877c86a0690c":{
      "scriptId":"u41"},
    "10dcd1a3445a4f469a1b684127182a2a":{
      "scriptId":"u42"},
    "912bdc71d3df4154bebb744e79c0bb5f":{
      "scriptId":"u43"},
    "d08b1f0846f14c1396215f1ab29962da":{
      "scriptId":"u44"},
    "d99a88480eb24be88b45567e8970fb34":{
      "scriptId":"u45"},
    "17ad60574f2245489d274f271e88d47e":{
      "scriptId":"u46"},
    "cdac54d781004c04a4564d8c6f327547":{
      "scriptId":"u47"},
    "436039ca777345e194bf325fe8db2931":{
      "scriptId":"u48"},
    "73b1f7451bf545c091a8c3b8294e59f5":{
      "scriptId":"u49"},
    "efac9e425db9418db8be04aa4d41c7e7":{
      "scriptId":"u50"},
    "886923b7999048d28c20580f28a04db4":{
      "scriptId":"u51"},
    "ef77795cc196408cbfd95158ee528c4b":{
      "scriptId":"u52"},
    "0d9526f302da4ac8b4d27a78bc454b52":{
      "scriptId":"u53"},
    "b240984edddb480aaec40435a0b02a32":{
      "scriptId":"u54"},
    "9510dd8e6374426fb852eff176a1f36a":{
      "scriptId":"u55"},
    "016ff16f5ab94295904a63873d98c8a1":{
      "scriptId":"u56"},
    "d9c907d1b6d24e1e887114dac7eca173":{
      "scriptId":"u57"},
    "2d1fc7b9b5964044bcb7ed1325bf2a6f":{
      "scriptId":"u58"},
    "aee3829b2ded49a893af764c01a3f70c":{
      "scriptId":"u59"},
    "ee466a4ef35e4c00bacba70a2fa22ef0":{
      "scriptId":"u60"}}});