$axure.loadCurrentPage({
  "url":"play-setting.html",
  "generationDate":new Date(1459858381027.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"37a9b3807f30479ab6913b95e05dc049",
    "type":"Axure:Page",
    "name":"play-setting",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a8dac9c683bb418ba2c45635584de838",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":183},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d09f48e79ba2483393c2b97578215cb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":111,
                  "y":183},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"3946f30ae4df4862873ac1a3d1b38007",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":111,
              "y":28},
            "size":{
              "width":39,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec61a29cb9d344aa8ecd5ee1149d938c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":111,
                  "y":28},
                "size":{
                  "width":39,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa6b2fd5c5444be0b80f515caed77213",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":56},
            "size":{
              "width":39,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26505dabd7a7433bbde4aa9925984d50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":56},
                "size":{
                  "width":39,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2dc39eb32ee344129e339c8c0fefc859",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":52},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"edd9ed3220da494fbb71050c0f98d0b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":91},
            "size":{
              "width":27,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"319f4562ffca498d86f2d72c61429f00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":91},
                "size":{
                  "width":27,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1063d3485d7349178add748e56790e92",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":84},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"34f16faee2b3498fb341aac7580938bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":123},
            "size":{
              "width":52,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d35501581734e7e8919cfa9e6c13c89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":123},
                "size":{
                  "width":52,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4ffbbd081474fb0892fea84d06fbc4d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":116},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d4bf3830a2d547abad6a6ca6d5d6ef0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":245,
              "y":148},
            "size":{
              "width":167,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4db8ee7ae24f43249fc038128aaad342",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":245,
                  "y":148},
                "size":{
                  "width":167,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1abb2e86e5f4cb2a13f6ec46203fb45",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":54},
            "size":{
              "width":27,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17bc04f749bd4af2a100c60c7724dc73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":54},
                "size":{
                  "width":27,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a7d73c1491a4e5a838dae5712a579ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":365,
              "y":183},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1b4ae85d0d44c85acf7dee0ed5293b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":365,
                  "y":183},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"ef2a2cc32f9342f69efbba356921585e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":111,
              "y":2},
            "size":{
              "width":98,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26e246437d424c068316d38a9f8a8f1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":111,
                  "y":2},
                "size":{
                  "width":98,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a8dac9c683bb418ba2c45635584de838":{
      "scriptId":"u0"},
    "d09f48e79ba2483393c2b97578215cb2":{
      "scriptId":"u1"},
    "3946f30ae4df4862873ac1a3d1b38007":{
      "scriptId":"u2"},
    "ec61a29cb9d344aa8ecd5ee1149d938c":{
      "scriptId":"u3"},
    "aa6b2fd5c5444be0b80f515caed77213":{
      "scriptId":"u4"},
    "26505dabd7a7433bbde4aa9925984d50":{
      "scriptId":"u5"},
    "2dc39eb32ee344129e339c8c0fefc859":{
      "scriptId":"u6"},
    "edd9ed3220da494fbb71050c0f98d0b3":{
      "scriptId":"u7"},
    "319f4562ffca498d86f2d72c61429f00":{
      "scriptId":"u8"},
    "1063d3485d7349178add748e56790e92":{
      "scriptId":"u9"},
    "34f16faee2b3498fb341aac7580938bd":{
      "scriptId":"u10"},
    "9d35501581734e7e8919cfa9e6c13c89":{
      "scriptId":"u11"},
    "e4ffbbd081474fb0892fea84d06fbc4d":{
      "scriptId":"u12"},
    "d4bf3830a2d547abad6a6ca6d5d6ef0f":{
      "scriptId":"u13"},
    "4db8ee7ae24f43249fc038128aaad342":{
      "scriptId":"u14"},
    "a1abb2e86e5f4cb2a13f6ec46203fb45":{
      "scriptId":"u15"},
    "17bc04f749bd4af2a100c60c7724dc73":{
      "scriptId":"u16"},
    "7a7d73c1491a4e5a838dae5712a579ff":{
      "scriptId":"u17"},
    "a1b4ae85d0d44c85acf7dee0ed5293b4":{
      "scriptId":"u18"},
    "ef2a2cc32f9342f69efbba356921585e":{
      "scriptId":"u19"},
    "26e246437d424c068316d38a9f8a8f1e":{
      "scriptId":"u20"}}});