$axure.loadCurrentPage({
  "url":"about.html",
  "generationDate":new Date(1459858381449.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"08fe65e13b894ecf8e941a612a232b6f",
    "type":"Axure:Page",
    "name":"about",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a8dac9c683bb418ba2c45635584de838",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":250},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d09f48e79ba2483393c2b97578215cb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":250},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"948fdba3aa904c6b874793899c6f7e3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":43},
            "size":{
              "width":134,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82fd75862a754a2cb33f2a686b54e218",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":43},
                "size":{
                  "width":134,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b0df070fe4249edae5bf0b0a3932633",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":68},
            "size":{
              "width":240,
              "height":159}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1f088d1058c446f7a503cb5717670000",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9ce7eda9c6364d5190615c5e86465357",
                  "label":"",
                  "parentDynamicPanel":"5b0df070fe4249edae5bf0b0a3932633",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":3,
                      "y":2},
                    "size":{
                      "width":113,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5e798df615584329ad9fe676b947b701",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5b0df070fe4249edae5bf0b0a3932633",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":3,
                          "y":2},
                        "size":{
                          "width":113,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to Next",
                              "panelsToStates":[{
                                  "panelPath":["5b0df070fe4249edae5bf0b0a3932633"],
                                  "stateInfo":{
                                    "setStateType":"next",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"e0fefb5457eb414880c76d3990ac732d",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7b11130cd66f4fbaa3e9fad7ca1d5338",
                  "label":"",
                  "parentDynamicPanel":"5b0df070fe4249edae5bf0b0a3932633",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":1},
                    "size":{
                      "width":134,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1af3e4384c224b8dbce8455e66537798",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5b0df070fe4249edae5bf0b0a3932633",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":1,
                          "y":1},
                        "size":{
                          "width":134,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b121b37812c94aeea9019b42273a5ac5",
                  "label":"",
                  "parentDynamicPanel":"5b0df070fe4249edae5bf0b0a3932633",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":36},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"62214aeae4934d6eb6cd2086282eec98",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5b0df070fe4249edae5bf0b0a3932633",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":1,
                          "y":36},
                        "size":{
                          "width":300,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"81c62e68274e4b848ee405a6e3010172",
                  "label":"",
                  "parentDynamicPanel":"5b0df070fe4249edae5bf0b0a3932633",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":1,
                      "y":86},
                    "size":{
                      "width":100,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"829cbf993f8f4d1c84ed225d69efe99d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5b0df070fe4249edae5bf0b0a3932633",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":1,
                          "y":86},
                        "size":{
                          "width":100,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Show (Dynamic Panel)",
                              "objectsToFades":[{
                                  "objectPath":["e606b46cd97448f992d65c4f3867efe1"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/login/u9.png"}}]}]},
{
          "id":"e606b46cd97448f992d65c4f3867efe1",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":160,
              "y":68},
            "size":{
              "width":380,
              "height":130},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onPanelStateChange":{
              "description":"OnPanelStateChange",
              "cases":[{
                  "description":"Case 1<br> (If state of This equals State2)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["e606b46cd97448f992d65c4f3867efe1"],
                      "panelIndex":1}},
                  "actions":[{
                      "action":"wait",
                      "description":"Wait 2000 ms",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to Next",
                      "panelsToStates":[{
                          "panelPath":["e606b46cd97448f992d65c4f3867efe1"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"Case 1<br> (Else If state of This equals State4)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetPanelState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"panelDiagramLiteral",
                      "panelPath":["e606b46cd97448f992d65c4f3867efe1"],
                      "panelIndex":2}},
                  "actions":[{
                      "action":"wait",
                      "description":"Wait 2000 ms",
                      "waitTime":2000},
{
                      "action":"setPanelState",
                      "description":"Set (Dynamic Panel) to Next",
                      "panelsToStates":[{
                          "panelPath":["e606b46cd97448f992d65c4f3867efe1"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e8bb0657f0a34339a764aec876e464fc",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"854a5cae54834995b9d15afb34b75e19",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":380,
                      "height":130}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ebcef45f5def489a9864c95f43f467e6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":380,
                          "height":130}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/update/u5.png"}},
{
                  "id":"b1b32ed85efb432f9407a8371076f7c0",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":5,
                      "y":4},
                    "size":{
                      "width":52,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ecfcdd11ac4c470688e114fcafc59894",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":5,
                          "y":4},
                        "size":{
                          "width":52,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b510d888ce3449db8f1801d83f043978",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":5,
                      "y":19},
                    "size":{
                      "width":365,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/update/u9_line.png"}},
{
                  "id":"bc0369271ac043aba6a72254189067c9",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":354,
                      "y":4},
                    "size":{
                      "width":10,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f7de4bb42e30466e89c526fc3449305c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":354,
                          "y":4},
                        "size":{
                          "width":10,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Hide (Dynamic Panel)",
                              "objectsToFades":[{
                                  "objectPath":["e606b46cd97448f992d65c4f3867efe1"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a46d9fec01184bf586cfebafddc10c5b",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":58,
                      "y":50},
                    "size":{
                      "width":257,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8c0592e84d4647c88472cf01eed8c9de",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":58,
                          "y":50},
                        "size":{
                          "width":257,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"190600c383a9496885d62ed7d87dbd83",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":136,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d52a51acb97465582639679a7fb5544",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":136,
                          "y":90},
                        "size":{
                          "width":100,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to Next",
                              "panelsToStates":[{
                                  "panelPath":["e606b46cd97448f992d65c4f3867efe1"],
                                  "stateInfo":{
                                    "setStateType":"next",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/login/u9.png"}}]},
{
              "id":"92f02406570142bcbd7935a86b8bd2e3",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1eddae10b2d54bc98dc5ef8975ee7326",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":380,
                      "height":130}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2a2b1cdee7a64382a312ce27626e45c6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":380,
                          "height":130}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onShow":{
                      "description":"OnShow",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"wait",
                              "description":"Wait 1000 ms",
                              "waitTime":1000},
{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to Next",
                              "panelsToStates":[{
                                  "panelPath":["e606b46cd97448f992d65c4f3867efe1"],
                                  "stateInfo":{
                                    "setStateType":"next",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/update/u5.png"}},
{
                  "id":"b5380e3653264cc7b55c918a33bd1df2",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":5,
                      "y":4},
                    "size":{
                      "width":52,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b20a6c3aa88a4a00b1719d2703f2b7be",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":5,
                          "y":4},
                        "size":{
                          "width":52,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ba4deb264aae40b59f2a94b6413fae41",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":5,
                      "y":19},
                    "size":{
                      "width":365,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/update/u9_line.png"}},
{
                  "id":"51954c15a7cc4bde8b2400dc0d5ef685",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":50},
                    "size":{
                      "width":310,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c566d551f14943eea916a2a6ffd29bc0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":50},
                        "size":{
                          "width":310,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/update/u21.png"}},
{
                  "id":"f9c52ee325e24fea82dd5d61c36f32fd",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":30,
                      "y":50},
                    "size":{
                      "width":140,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4e1bfd6a7097492f826acc31ea182ba1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF0066FF},
                        "location":{
                          "x":30,
                          "y":50},
                        "size":{
                          "width":140,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/update/u23.png"}}]},
{
              "id":"43eb9d915a6346bf992cbd8649c951e0",
              "label":"State4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7380fff5ce4544f89b61df7214bcbd31",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":380,
                      "height":130}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aacb3f9f9c2b426caeb5f40144cf0fa6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":380,
                          "height":130}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onShow":{
                      "description":"OnShow",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"wait",
                              "description":"Wait 1000 ms",
                              "waitTime":1000},
{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to Next",
                              "panelsToStates":[{
                                  "panelPath":["e606b46cd97448f992d65c4f3867efe1"],
                                  "stateInfo":{
                                    "setStateType":"next",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/update/u5.png"}},
{
                  "id":"2c733c39445040b1bd2a88f30ca52795",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":5,
                      "y":4},
                    "size":{
                      "width":52,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"10f7e218857a49bba8a6f5190a03b1b1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":5,
                          "y":4},
                        "size":{
                          "width":52,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9143a40e6c9b4c42a8b2b0f52e1711e3",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":5,
                      "y":19},
                    "size":{
                      "width":365,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/update/u9_line.png"}},
{
                  "id":"6488066c2f7e4714bf8345084d4a0755",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":50},
                    "size":{
                      "width":310,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df20ccf8d8844f4992e454c070e22d7b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":50},
                        "size":{
                          "width":310,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/update/u21.png"}},
{
                  "id":"13a2d1f31bd34cec8e82243ccd195e6d",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF},
                    "location":{
                      "x":30,
                      "y":50},
                    "size":{
                      "width":140,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f456529b8e8f4649a1faa6db621a9755",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF0066FF},
                        "location":{
                          "x":30,
                          "y":50},
                        "size":{
                          "width":140,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/update/u23.png"}}]},
{
              "id":"6102e23eb995455a957b1f67876561bf",
              "label":"State3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1fa1806ed9fd48a7866d72c490c4a0a7",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":380,
                      "height":130}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f100bca779814cd08f5bef0436b76232",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":380,
                          "height":130}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/update/u5.png"}},
{
                  "id":"2399787a88f8462cb9810b54b8c2e26c",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":5,
                      "y":4},
                    "size":{
                      "width":52,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dc668a4e1ba3414d985f67a3ff2fe1be",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":5,
                          "y":4},
                        "size":{
                          "width":52,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0972e2704fcb4374888ea4000cf11368",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":5,
                      "y":19},
                    "size":{
                      "width":365,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/update/u9_line.png"}},
{
                  "id":"a3762ff79de141219d2159a044ada940",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":354,
                      "y":4},
                    "size":{
                      "width":10,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a9c90ba4ff6d4dca8ff298e685fca288",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":354,
                          "y":4},
                        "size":{
                          "width":10,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Hide (Dynamic Panel)",
                              "objectsToFades":[{
                                  "objectPath":["e606b46cd97448f992d65c4f3867efe1"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c8156f221774466bb4acff8dd09328df",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":58,
                      "y":50},
                    "size":{
                      "width":244,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"651d2cdb61694305bf5da5955e1ad3da",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":58,
                          "y":50},
                        "size":{
                          "width":244,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ab32615c06074f3795df770ab1b97488",
                  "label":"",
                  "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":136,
                      "y":90},
                    "size":{
                      "width":100,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f5f99f45a3144e609210dc041ec37a52",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e606b46cd97448f992d65c4f3867efe1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":136,
                          "y":90},
                        "size":{
                          "width":100,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Hide (Dynamic Panel)",
                              "objectsToFades":[{
                                  "objectPath":["e606b46cd97448f992d65c4f3867efe1"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/login/u9.png"}}]}]},
{
          "id":"1e1985835f05402ba3fd299f209e8bda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":11},
            "size":{
              "width":131,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ae54800d3fd4423bb249bc1a2cce455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":11},
                "size":{
                  "width":131,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a8dac9c683bb418ba2c45635584de838":{
      "scriptId":"u0"},
    "d09f48e79ba2483393c2b97578215cb2":{
      "scriptId":"u1"},
    "948fdba3aa904c6b874793899c6f7e3a":{
      "scriptId":"u2"},
    "82fd75862a754a2cb33f2a686b54e218":{
      "scriptId":"u3"},
    "5b0df070fe4249edae5bf0b0a3932633":{
      "scriptId":"u4"},
    "9ce7eda9c6364d5190615c5e86465357":{
      "scriptId":"u5"},
    "5e798df615584329ad9fe676b947b701":{
      "scriptId":"u6"},
    "7b11130cd66f4fbaa3e9fad7ca1d5338":{
      "scriptId":"u7"},
    "1af3e4384c224b8dbce8455e66537798":{
      "scriptId":"u8"},
    "b121b37812c94aeea9019b42273a5ac5":{
      "scriptId":"u9"},
    "62214aeae4934d6eb6cd2086282eec98":{
      "scriptId":"u10"},
    "81c62e68274e4b848ee405a6e3010172":{
      "scriptId":"u11"},
    "829cbf993f8f4d1c84ed225d69efe99d":{
      "scriptId":"u12"},
    "e606b46cd97448f992d65c4f3867efe1":{
      "scriptId":"u13"},
    "854a5cae54834995b9d15afb34b75e19":{
      "scriptId":"u14"},
    "ebcef45f5def489a9864c95f43f467e6":{
      "scriptId":"u15"},
    "b1b32ed85efb432f9407a8371076f7c0":{
      "scriptId":"u16"},
    "ecfcdd11ac4c470688e114fcafc59894":{
      "scriptId":"u17"},
    "b510d888ce3449db8f1801d83f043978":{
      "scriptId":"u18"},
    "bc0369271ac043aba6a72254189067c9":{
      "scriptId":"u19"},
    "f7de4bb42e30466e89c526fc3449305c":{
      "scriptId":"u20"},
    "a46d9fec01184bf586cfebafddc10c5b":{
      "scriptId":"u21"},
    "8c0592e84d4647c88472cf01eed8c9de":{
      "scriptId":"u22"},
    "190600c383a9496885d62ed7d87dbd83":{
      "scriptId":"u23"},
    "7d52a51acb97465582639679a7fb5544":{
      "scriptId":"u24"},
    "1eddae10b2d54bc98dc5ef8975ee7326":{
      "scriptId":"u25"},
    "2a2b1cdee7a64382a312ce27626e45c6":{
      "scriptId":"u26"},
    "b5380e3653264cc7b55c918a33bd1df2":{
      "scriptId":"u27"},
    "b20a6c3aa88a4a00b1719d2703f2b7be":{
      "scriptId":"u28"},
    "ba4deb264aae40b59f2a94b6413fae41":{
      "scriptId":"u29"},
    "51954c15a7cc4bde8b2400dc0d5ef685":{
      "scriptId":"u30"},
    "c566d551f14943eea916a2a6ffd29bc0":{
      "scriptId":"u31"},
    "f9c52ee325e24fea82dd5d61c36f32fd":{
      "scriptId":"u32"},
    "4e1bfd6a7097492f826acc31ea182ba1":{
      "scriptId":"u33"},
    "7380fff5ce4544f89b61df7214bcbd31":{
      "scriptId":"u34"},
    "aacb3f9f9c2b426caeb5f40144cf0fa6":{
      "scriptId":"u35"},
    "2c733c39445040b1bd2a88f30ca52795":{
      "scriptId":"u36"},
    "10f7e218857a49bba8a6f5190a03b1b1":{
      "scriptId":"u37"},
    "9143a40e6c9b4c42a8b2b0f52e1711e3":{
      "scriptId":"u38"},
    "6488066c2f7e4714bf8345084d4a0755":{
      "scriptId":"u39"},
    "df20ccf8d8844f4992e454c070e22d7b":{
      "scriptId":"u40"},
    "13a2d1f31bd34cec8e82243ccd195e6d":{
      "scriptId":"u41"},
    "f456529b8e8f4649a1faa6db621a9755":{
      "scriptId":"u42"},
    "1fa1806ed9fd48a7866d72c490c4a0a7":{
      "scriptId":"u43"},
    "f100bca779814cd08f5bef0436b76232":{
      "scriptId":"u44"},
    "2399787a88f8462cb9810b54b8c2e26c":{
      "scriptId":"u45"},
    "dc668a4e1ba3414d985f67a3ff2fe1be":{
      "scriptId":"u46"},
    "0972e2704fcb4374888ea4000cf11368":{
      "scriptId":"u47"},
    "a3762ff79de141219d2159a044ada940":{
      "scriptId":"u48"},
    "a9c90ba4ff6d4dca8ff298e685fca288":{
      "scriptId":"u49"},
    "c8156f221774466bb4acff8dd09328df":{
      "scriptId":"u50"},
    "651d2cdb61694305bf5da5955e1ad3da":{
      "scriptId":"u51"},
    "ab32615c06074f3795df770ab1b97488":{
      "scriptId":"u52"},
    "f5f99f45a3144e609210dc041ec37a52":{
      "scriptId":"u53"},
    "1e1985835f05402ba3fd299f209e8bda":{
      "scriptId":"u54"},
    "7ae54800d3fd4423bb249bc1a2cce455":{
      "scriptId":"u55"}}});