$axure.loadCurrentPage({
  "url":"wifi-detail-setting.html",
  "generationDate":new Date(1459858381256.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0c13e91ef0284d17bb09b51d9b368077",
    "type":"Axure:Page",
    "name":"Wifi-detail-setting",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a8dac9c683bb418ba2c45635584de838",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":328},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d09f48e79ba2483393c2b97578215cb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":328},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"2d2dc3bee17b484ab5bc9efc22508a93",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":131,
              "y":40},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd1324e503d045b5ad7349dd006f83d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8ae64f5ebd6d4929a6ee2d09013427fb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "size":{
                      "width":330,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u3.png"}}]},
{
          "id":"6f439e26c0ad4d4b9e3e929af818d0cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":131,
              "y":80},
            "size":{
              "width":27,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a6f43bc8efc4314a368e5bd17719859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":131,
                  "y":80},
                "size":{
                  "width":27,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99a542ab0f50476db18eb06a6215dbde",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":131,
              "y":117},
            "size":{
              "width":51,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"974ba458d2894ecb9df9a18fb57bcd5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":131,
                  "y":117},
                "size":{
                  "width":51,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"858f8992ac2e472bbfe7478d4046de4f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":131,
              "y":135},
            "size":{
              "width":330,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06732eec7dbd44ff8120eca7e5b1a964",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"93bdeaac61f94de1bcd63ee1842389a0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u10.png"}},
{
              "id":"3d32efb46e414a5e803f691eec773fc3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bb965c178683419ca2240d022e14a4d9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u10.png"}},
{
              "id":"64bd1c8a43514a47a784ef239bc41da8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1bcbaca7b6dd4515b0e832b32aa2d58c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u10.png"}},
{
              "id":"4b1f94daf6c741de88a2104a3b33deaa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":0},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1afe9f6a34d44c9844c1dbef7b34c0a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":0},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u12.png"}},
{
              "id":"cb9fb1748ef5415087396fa5ea63d8b4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":30},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c3f973fefb614b95a01c4ac0cf76ba78",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":30},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u12.png"}},
{
              "id":"88c07188026c4c6398d33a2661219c36",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":60},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7d5e2c1c0b9044bca9cd3bb43278f3bd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":60},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u12.png"}},
{
              "id":"a527c55173c04f2b8a8965b203407daa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"472976e04ce64206bb7c45a0fe7dc611",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u10.png"}},
{
              "id":"d363ab9a63b44372aba4a6f97e60359a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":90},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c1577348356a444998b226246fe73561",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":90},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u12.png"}},
{
              "id":"684bfeef93bd443e8e84db5fd8fd9a8e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bdfb7e7cc60b4b07bbe60bce0e445960",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u10.png"}},
{
              "id":"39fed53af043431f82b81e4ee0a660d1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":120},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2a223b925c204608a776448b70707e8e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":120},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u12.png"}},
{
              "id":"82423ecea7cf4d50838d9bf60f5e2816",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ffc74c71737b4140ac6529ecfd5bb1e0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u30.png"}},
{
              "id":"cfdc2646a6284b9dafafb4c8f0ab4e20",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":150},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"78010157a9044f07aa59c2fd668e4a18",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":150},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u32.png"}}]},
{
          "id":"37700cd408c94176bfbeb8652bdfd8b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":11},
            "size":{
              "width":212,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef0dcf04eba469da46bf2899c7f8f60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":11},
                "size":{
                  "width":212,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5148cfd2063e4bf897fc8711c962912c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":328},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e74efc469b14d50924fe84b99bdcd71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":328},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"c92e3934103245ccb22ab0eff3f7d8c5",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":48},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"717e385a81ad44478858059ad46e4ef1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":48},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"bc60ebf1029d468f9825f9bb8ac6bfab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":131,
              "y":99},
            "size":{
              "width":147,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a1e60d649464d0e9e7407cc9aeab9e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":131,
                  "y":99},
                "size":{
                  "width":147,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a8dac9c683bb418ba2c45635584de838":{
      "scriptId":"u0"},
    "d09f48e79ba2483393c2b97578215cb2":{
      "scriptId":"u1"},
    "2d2dc3bee17b484ab5bc9efc22508a93":{
      "scriptId":"u2"},
    "bd1324e503d045b5ad7349dd006f83d8":{
      "scriptId":"u3"},
    "8ae64f5ebd6d4929a6ee2d09013427fb":{
      "scriptId":"u4"},
    "6f439e26c0ad4d4b9e3e929af818d0cf":{
      "scriptId":"u5"},
    "1a6f43bc8efc4314a368e5bd17719859":{
      "scriptId":"u6"},
    "99a542ab0f50476db18eb06a6215dbde":{
      "scriptId":"u7"},
    "974ba458d2894ecb9df9a18fb57bcd5e":{
      "scriptId":"u8"},
    "858f8992ac2e472bbfe7478d4046de4f":{
      "scriptId":"u9"},
    "06732eec7dbd44ff8120eca7e5b1a964":{
      "scriptId":"u10"},
    "93bdeaac61f94de1bcd63ee1842389a0":{
      "scriptId":"u11"},
    "4b1f94daf6c741de88a2104a3b33deaa":{
      "scriptId":"u12"},
    "b1afe9f6a34d44c9844c1dbef7b34c0a":{
      "scriptId":"u13"},
    "3d32efb46e414a5e803f691eec773fc3":{
      "scriptId":"u14"},
    "bb965c178683419ca2240d022e14a4d9":{
      "scriptId":"u15"},
    "cb9fb1748ef5415087396fa5ea63d8b4":{
      "scriptId":"u16"},
    "c3f973fefb614b95a01c4ac0cf76ba78":{
      "scriptId":"u17"},
    "64bd1c8a43514a47a784ef239bc41da8":{
      "scriptId":"u18"},
    "1bcbaca7b6dd4515b0e832b32aa2d58c":{
      "scriptId":"u19"},
    "88c07188026c4c6398d33a2661219c36":{
      "scriptId":"u20"},
    "7d5e2c1c0b9044bca9cd3bb43278f3bd":{
      "scriptId":"u21"},
    "a527c55173c04f2b8a8965b203407daa":{
      "scriptId":"u22"},
    "472976e04ce64206bb7c45a0fe7dc611":{
      "scriptId":"u23"},
    "d363ab9a63b44372aba4a6f97e60359a":{
      "scriptId":"u24"},
    "c1577348356a444998b226246fe73561":{
      "scriptId":"u25"},
    "684bfeef93bd443e8e84db5fd8fd9a8e":{
      "scriptId":"u26"},
    "bdfb7e7cc60b4b07bbe60bce0e445960":{
      "scriptId":"u27"},
    "39fed53af043431f82b81e4ee0a660d1":{
      "scriptId":"u28"},
    "2a223b925c204608a776448b70707e8e":{
      "scriptId":"u29"},
    "82423ecea7cf4d50838d9bf60f5e2816":{
      "scriptId":"u30"},
    "ffc74c71737b4140ac6529ecfd5bb1e0":{
      "scriptId":"u31"},
    "cfdc2646a6284b9dafafb4c8f0ab4e20":{
      "scriptId":"u32"},
    "78010157a9044f07aa59c2fd668e4a18":{
      "scriptId":"u33"},
    "37700cd408c94176bfbeb8652bdfd8b2":{
      "scriptId":"u34"},
    "8ef0dcf04eba469da46bf2899c7f8f60":{
      "scriptId":"u35"},
    "5148cfd2063e4bf897fc8711c962912c":{
      "scriptId":"u36"},
    "9e74efc469b14d50924fe84b99bdcd71":{
      "scriptId":"u37"},
    "c92e3934103245ccb22ab0eff3f7d8c5":{
      "scriptId":"u38"},
    "717e385a81ad44478858059ad46e4ef1":{
      "scriptId":"u39"},
    "bc60ebf1029d468f9825f9bb8ac6bfab":{
      "scriptId":"u40"},
    "8a1e60d649464d0e9e7407cc9aeab9e9":{
      "scriptId":"u41"}}});