$axure.loadCurrentPage({
  "url":"main.html",
  "generationDate":new Date(1459858380946.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3ad847290cfa4bf691612a02bf831a68",
    "type":"Axure:Page",
    "name":"main",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d8d44160b2a94a25b86919f4d9ad5749",
          "label":"main_frame",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":70},
            "size":{
              "width":570,
              "height":370}},
          "adaptiveStyles":{
}},
{
          "id":"746d7c0c8eeb48ba93a74f5824d20565",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":10},
            "size":{
              "width":400,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fee588618eb4e46868ebaf19267274e",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":400,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1459bd606f544d8ca404e9c85d6201a0",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6c92afee076a4ea58a6efe227fddf00f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":100,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkFrame",
                              "description":"Open play-setting in main_frame",
                              "linkType":"frame",
                              "framesToTargets":[{
                                  "framePath":["d8d44160b2a94a25b86919f4d9ad5749"],
                                  "target":{
                                    "targetType":"page",
                                    "url":"play-setting.html",
                                    "includeVariables":true}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/main/u3.png"}},
{
                  "id":"53b0c71a576f4a1e9719bb64edf311a0",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a2c7abf2903d455a8654cd26c0bf6102",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":200,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkFrame",
                              "description":"Open net-setting in main_frame",
                              "linkType":"frame",
                              "framesToTargets":[{
                                  "framePath":["d8d44160b2a94a25b86919f4d9ad5749"],
                                  "target":{
                                    "targetType":"page",
                                    "url":"net-setting.html",
                                    "includeVariables":true}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/main/u3.png"}},
{
                  "id":"934873d24c2b40548ac0eaa1ecb36575",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"deb0923391a54822a4916d6c0a96b43c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":300,
                          "y":0},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkFrame",
                              "description":"Open sys-setting in main_frame",
                              "linkType":"frame",
                              "framesToTargets":[{
                                  "framePath":["d8d44160b2a94a25b86919f4d9ad5749"],
                                  "target":{
                                    "targetType":"page",
                                    "url":"sys-setting.html",
                                    "includeVariables":true}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/main/u9.png"}},
{
                  "id":"ae6dc936964d447085bf0a6c287ec55a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c1669379d1f140a784c3f0dde92d4b59",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":100,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkFrame",
                              "description":"Open play in main_frame",
                              "linkType":"frame",
                              "framesToTargets":[{
                                  "framePath":["d8d44160b2a94a25b86919f4d9ad5749"],
                                  "target":{
                                    "targetType":"page",
                                    "url":"play.html",
                                    "includeVariables":true}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/main/u3.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "d8d44160b2a94a25b86919f4d9ad5749":{
      "scriptId":"u0"},
    "746d7c0c8eeb48ba93a74f5824d20565":{
      "scriptId":"u1"},
    "8fee588618eb4e46868ebaf19267274e":{
      "scriptId":"u2"},
    "ae6dc936964d447085bf0a6c287ec55a":{
      "scriptId":"u3"},
    "c1669379d1f140a784c3f0dde92d4b59":{
      "scriptId":"u4"},
    "1459bd606f544d8ca404e9c85d6201a0":{
      "scriptId":"u5"},
    "6c92afee076a4ea58a6efe227fddf00f":{
      "scriptId":"u6"},
    "53b0c71a576f4a1e9719bb64edf311a0":{
      "scriptId":"u7"},
    "a2c7abf2903d455a8654cd26c0bf6102":{
      "scriptId":"u8"},
    "934873d24c2b40548ac0eaa1ecb36575":{
      "scriptId":"u9"},
    "deb0923391a54822a4916d6c0a96b43c":{
      "scriptId":"u10"}}});