$axure.loadCurrentPage({
  "url":"play.html",
  "generationDate":new Date(1459858381010.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"403bffda316346ed84b47b7f22ca2dc6",
    "type":"Axure:Page",
    "name":"play",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9eee6707d96f4d0fa5c9738dc42c8ecf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200.5,
              "y":338.5},
            "size":{
              "width":120,
              "height":32},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b94ece9b24944769b9a420782049431",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200.5,
                  "y":338.5},
                "size":{
                  "width":120,
                  "height":32},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1<br> (If visibility of live-flag equals false)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["661791d72c7b4d9e8680e8f3726fab2a"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":false}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on This equal to &quot;结束直播&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"结束直播",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"fadeWidget",
                      "description":"Show live-flag",
                      "objectsToFades":[{
                          "objectPath":["661791d72c7b4d9e8680e8f3726fab2a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]},
{
                  "description":"Case 2<br> (Else If visibility of live-flag equals true)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetWidgetVisibility",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["661791d72c7b4d9e8680e8f3726fab2a"]}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on This equal to &quot;开播&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":true,
                                "isFocused":false,
                                "isTarget":false},
{
                                "exprType":"stringLiteral",
                                "value":"开播",
                                "stos":[]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}},
{
                      "action":"fadeWidget",
                      "description":"Hide live-flag",
                      "objectsToFades":[{
                          "objectPath":["661791d72c7b4d9e8680e8f3726fab2a"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/play/u0.png"}},
{
          "id":"805c99ddf4104c15a529f4a8de863280",
          "label":"live",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":-9,
              "y":-10},
            "size":{
              "width":539,
              "height":260}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d886458b63284a62b9999f90bd287210",
              "label":"开播",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bf0c05645ed445399063133dc3d6d200",
                  "label":"",
                  "parentDynamicPanel":"805c99ddf4104c15a529f4a8de863280",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":540,
                      "height":260}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c572a76924a64ac7a843f6527c91d79a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"805c99ddf4104c15a529f4a8de863280",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":540,
                          "height":260}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/play/u3.jpg"}}]}]},
{
          "id":"661791d72c7b4d9e8680e8f3726fab2a",
          "label":"live-flag",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":466,
              "y":-3},
            "size":{
              "width":58,
              "height":30},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"Set live-flag to Next wrap repeat every 1000 ms",
                      "panelsToStates":[{
                          "panelPath":["661791d72c7b4d9e8680e8f3726fab2a"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":1000,
                            "options":{
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"4486bb55e5c4481f96c77192fd6071e4",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"665bbeda2e444dccb2ef852fcc43ab7e",
                  "label":"",
                  "parentDynamicPanel":"661791d72c7b4d9e8680e8f3726fab2a",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "size":{
                      "width":49,
                      "height":29}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b36bc673418d44cebb82e057d8d7454b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"661791d72c7b4d9e8680e8f3726fab2a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "size":{
                          "width":49,
                          "height":29}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"51d5f1ace0ab4288a9ca05ed4793c29e",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"8aa29897bb1144e0900131b91b32780c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":16,
              "y":251},
            "size":{
              "width":47,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6943dbac7c384189b5286128268edd72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":16,
                  "y":251},
                "size":{
                  "width":47,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"415f8253d3b1464e82c3b175f0c58123",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":34},
            "size":{
              "width":15,
              "height":452},
            "rotation":"90",
            "textRotation":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c9dc8e4ef3e4103b90109f5aadc94f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":34},
                "size":{
                  "width":15,
                  "height":452},
                "rotation":"90",
                "textRotation":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/play/u10.png"}},
{
          "id":"5c4f6ef9e0dd46fa841f9fc0c4c694f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":272},
            "size":{
              "width":51,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93785cf837c4413fb5088fd4caf456df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":15,
                  "y":272},
                "size":{
                  "width":51,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4724dc054b0744488cfd1d0d0e8ac9f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":54},
            "size":{
              "width":15,
              "height":452},
            "rotation":"90",
            "textRotation":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b121f34552745648f520bded2b9529d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":54},
                "size":{
                  "width":15,
                  "height":452},
                "rotation":"90",
                "textRotation":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/play/u10.png"}},
{
          "id":"ced5fffda1744d6093f19d8007499dd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":14,
              "y":293},
            "size":{
              "width":35,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f36e599e19084c0785e5b30306fac5ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":14,
                  "y":293},
                "size":{
                  "width":35,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd13c8b297f54f56ace41778c1abf7fd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":285,
              "y":75},
            "size":{
              "width":15,
              "height":452},
            "rotation":"90",
            "textRotation":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc43acb32fde47a6afc173d1ae389db8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":285,
                  "y":75},
                "size":{
                  "width":15,
                  "height":452},
                "rotation":"90",
                "textRotation":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/play/u10.png"}},
{
          "id":"568b39311bfb4bacb38cdf40dd0df325",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":13,
              "y":313},
            "size":{
              "width":45,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b27cc8f4b3c40c2bd8486fc89875ffa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":13,
                  "y":313},
                "size":{
                  "width":45,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19c30a721fb24d9d89234d50566eb778",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":284,
              "y":95},
            "size":{
              "width":15,
              "height":452},
            "rotation":"90",
            "textRotation":"90"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9ab18ccafbe427694c8885c518d9ae8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":284,
                  "y":95},
                "size":{
                  "width":15,
                  "height":452},
                "rotation":"90",
                "textRotation":"90"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/play/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9eee6707d96f4d0fa5c9738dc42c8ecf":{
      "scriptId":"u0"},
    "7b94ece9b24944769b9a420782049431":{
      "scriptId":"u1"},
    "805c99ddf4104c15a529f4a8de863280":{
      "scriptId":"u2"},
    "bf0c05645ed445399063133dc3d6d200":{
      "scriptId":"u3"},
    "c572a76924a64ac7a843f6527c91d79a":{
      "scriptId":"u4"},
    "661791d72c7b4d9e8680e8f3726fab2a":{
      "scriptId":"u5"},
    "665bbeda2e444dccb2ef852fcc43ab7e":{
      "scriptId":"u6"},
    "b36bc673418d44cebb82e057d8d7454b":{
      "scriptId":"u7"},
    "8aa29897bb1144e0900131b91b32780c":{
      "scriptId":"u8"},
    "6943dbac7c384189b5286128268edd72":{
      "scriptId":"u9"},
    "415f8253d3b1464e82c3b175f0c58123":{
      "scriptId":"u10"},
    "7c9dc8e4ef3e4103b90109f5aadc94f3":{
      "scriptId":"u11"},
    "5c4f6ef9e0dd46fa841f9fc0c4c694f9":{
      "scriptId":"u12"},
    "93785cf837c4413fb5088fd4caf456df":{
      "scriptId":"u13"},
    "4724dc054b0744488cfd1d0d0e8ac9f8":{
      "scriptId":"u14"},
    "0b121f34552745648f520bded2b9529d":{
      "scriptId":"u15"},
    "ced5fffda1744d6093f19d8007499dd4":{
      "scriptId":"u16"},
    "f36e599e19084c0785e5b30306fac5ec":{
      "scriptId":"u17"},
    "dd13c8b297f54f56ace41778c1abf7fd":{
      "scriptId":"u18"},
    "bc43acb32fde47a6afc173d1ae389db8":{
      "scriptId":"u19"},
    "568b39311bfb4bacb38cdf40dd0df325":{
      "scriptId":"u20"},
    "0b27cc8f4b3c40c2bd8486fc89875ffa":{
      "scriptId":"u21"},
    "19c30a721fb24d9d89234d50566eb778":{
      "scriptId":"u22"},
    "a9ab18ccafbe427694c8885c518d9ae8":{
      "scriptId":"u23"}}});