$axure.loadCurrentPage({
  "url":"wifi-setting.html",
  "generationDate":new Date(1459858381213.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c1f270e76af34d218c1167f8922dc4ae",
    "type":"Axure:Page",
    "name":"Wifi-setting",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a8dac9c683bb418ba2c45635584de838",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":260},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d09f48e79ba2483393c2b97578215cb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":260},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"9dd2d97ee5444d60988392cb9bf2c933",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":37},
            "size":{
              "width":27,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3635fabffda46be860fafde77311a5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":37},
                "size":{
                  "width":27,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b83284b84e2e4b3c81bf994d82023730",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":37},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cda0e8cd20954a46af06841008e9f04e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408,
                  "y":37},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"fc3d6592bad5439880bc172477f50613",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":72},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"689d929f96ef42faa24904ff868da38f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":72},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e112e2085ce54de09e117b977d822017",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":127},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a0ba92267064babac7ae0841c30695b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":127},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62440daf6581404dbf56696fbc3b1f48",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":152},
            "size":{
              "width":300,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1fec15dd532c4485ba19ecf354c95ee5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7158c68064a345028fe0b3f7d6503a5b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"Case 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"Open Wifi-detail-setting in Current Window",
                          "target":{
                            "targetType":"page",
                            "url":"wifi-detail-setting.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/wifi-setting/u11.png"}},
{
              "id":"026b1c8c965a45278bd718b90b77896d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b98dd21bd5b9401891489be395c3ce97",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"Case 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"Open Wifi-detail-setting in Current Window",
                          "target":{
                            "targetType":"page",
                            "url":"wifi-detail-setting.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/wifi-setting/u11.png"}},
{
              "id":"625cbb1d78a04abc8a0102541514a08b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":300,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abc28b778d3e43109f783c6d51b68238",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":300,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"Case 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"Open Wifi-hide-detail-setting in Current Window",
                          "target":{
                            "targetType":"page",
                            "url":"wifi-hide-detail-setting.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/wifi-setting/u15.png"}}]},
{
          "id":"576e60d854a2446db46aee6bd262b9e8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":156},
            "size":{
              "width":13,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4730837b53147dfaae3bc50b69b285f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":156},
                "size":{
                  "width":13,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wifi-setting/u17.jpg"}},
{
          "id":"330d304114d34c9cbf1a67c4cccd08ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":186},
            "size":{
              "width":13,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46a52cb629f0420fac0f56bfb63d45af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":186},
                "size":{
                  "width":13,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wifi-setting/u17.jpg"}},
{
          "id":"e3edf702db93411b8ea0f6b7e864f0a3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":386,
              "y":158},
            "size":{
              "width":13,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9499a40e59a34c759137039d3222f0f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":386,
                  "y":158},
                "size":{
                  "width":13,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/wifi-setting/u21.png"}},
{
          "id":"2b5d0c2f656244ffa275d03dc2cefaf7",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":93},
            "size":{
              "width":300,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8e69815509d4d5898f33dc6775c62e5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "size":{
                  "width":300,
                  "height":25}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f36255f45b2e4d3ba6fc9a4a51e56bb1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"middle",
                    "size":{
                      "width":300,
                      "height":25}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"Case 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"Open Wifi-detail-setting in Current Window",
                          "target":{
                            "targetType":"page",
                            "url":"wifi-detail-setting.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/wifi-setting/u24.png"}}]},
{
          "id":"48b9996eda9e4d448b0ef406573f8de4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":405,
              "y":96},
            "size":{
              "width":21,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bebb09538cf147aa82886505097186ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":405,
                  "y":96},
                "size":{
                  "width":21,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u47.png"}},
{
          "id":"6030fc08a45840d5b03609e064fc8d7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":11},
            "size":{
              "width":135,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66a0cf31e7ef40bdb70bbd6226b9a0d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":11},
                "size":{
                  "width":135,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a808145d42a4172aab81ffe8d7ae156",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":260},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d540d85f5dcd4e27af84d47da43f8999",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":260},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u9.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a8dac9c683bb418ba2c45635584de838":{
      "scriptId":"u0"},
    "d09f48e79ba2483393c2b97578215cb2":{
      "scriptId":"u1"},
    "9dd2d97ee5444d60988392cb9bf2c933":{
      "scriptId":"u2"},
    "c3635fabffda46be860fafde77311a5e":{
      "scriptId":"u3"},
    "b83284b84e2e4b3c81bf994d82023730":{
      "scriptId":"u4"},
    "cda0e8cd20954a46af06841008e9f04e":{
      "scriptId":"u5"},
    "fc3d6592bad5439880bc172477f50613":{
      "scriptId":"u6"},
    "689d929f96ef42faa24904ff868da38f":{
      "scriptId":"u7"},
    "e112e2085ce54de09e117b977d822017":{
      "scriptId":"u8"},
    "5a0ba92267064babac7ae0841c30695b":{
      "scriptId":"u9"},
    "62440daf6581404dbf56696fbc3b1f48":{
      "scriptId":"u10"},
    "1fec15dd532c4485ba19ecf354c95ee5":{
      "scriptId":"u11"},
    "7158c68064a345028fe0b3f7d6503a5b":{
      "scriptId":"u12"},
    "026b1c8c965a45278bd718b90b77896d":{
      "scriptId":"u13"},
    "b98dd21bd5b9401891489be395c3ce97":{
      "scriptId":"u14"},
    "625cbb1d78a04abc8a0102541514a08b":{
      "scriptId":"u15"},
    "abc28b778d3e43109f783c6d51b68238":{
      "scriptId":"u16"},
    "576e60d854a2446db46aee6bd262b9e8":{
      "scriptId":"u17"},
    "a4730837b53147dfaae3bc50b69b285f":{
      "scriptId":"u18"},
    "330d304114d34c9cbf1a67c4cccd08ef":{
      "scriptId":"u19"},
    "46a52cb629f0420fac0f56bfb63d45af":{
      "scriptId":"u20"},
    "e3edf702db93411b8ea0f6b7e864f0a3":{
      "scriptId":"u21"},
    "9499a40e59a34c759137039d3222f0f5":{
      "scriptId":"u22"},
    "2b5d0c2f656244ffa275d03dc2cefaf7":{
      "scriptId":"u23"},
    "c8e69815509d4d5898f33dc6775c62e5":{
      "scriptId":"u24"},
    "f36255f45b2e4d3ba6fc9a4a51e56bb1":{
      "scriptId":"u25"},
    "48b9996eda9e4d448b0ef406573f8de4":{
      "scriptId":"u26"},
    "bebb09538cf147aa82886505097186ac":{
      "scriptId":"u27"},
    "6030fc08a45840d5b03609e064fc8d7a":{
      "scriptId":"u28"},
    "66a0cf31e7ef40bdb70bbd6226b9a0d7":{
      "scriptId":"u29"},
    "7a808145d42a4172aab81ffe8d7ae156":{
      "scriptId":"u30"},
    "d540d85f5dcd4e27af84d47da43f8999":{
      "scriptId":"u31"}}});