$axure.loadCurrentPage({
  "url":"wifi-password.html",
  "generationDate":new Date(1459858381301.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"14a7284e87534d78aa4f09cc9da64500",
    "type":"Axure:Page",
    "name":"Wifi-password",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a8dac9c683bb418ba2c45635584de838",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":170},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d09f48e79ba2483393c2b97578215cb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":170},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"18c8427ce9414652a6e54fa659996feb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":51},
            "size":{
              "width":149,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39ac7c1fec7c4ae98246c530f3d28d12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":233,
                  "y":51},
                "size":{
                  "width":149,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"858f8992ac2e472bbfe7478d4046de4f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":81},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06732eec7dbd44ff8120eca7e5b1a964",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"93bdeaac61f94de1bcd63ee1842389a0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u30.png"}},
{
              "id":"4b1f94daf6c741de88a2104a3b33deaa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":0},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1afe9f6a34d44c9844c1dbef7b34c0a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":0},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u32.png"}}]},
{
          "id":"196d9969498b4f29aa66f21ce7985681",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":11},
            "size":{
              "width":212,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aa7aa15525b4b06b1730ed011b36f81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":11},
                "size":{
                  "width":212,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3d6dcde1cb84c77b7d0142f0679c10c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":170},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e66299265f464c258247ee6558c8b573",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":170},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u9.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a8dac9c683bb418ba2c45635584de838":{
      "scriptId":"u0"},
    "d09f48e79ba2483393c2b97578215cb2":{
      "scriptId":"u1"},
    "18c8427ce9414652a6e54fa659996feb":{
      "scriptId":"u2"},
    "39ac7c1fec7c4ae98246c530f3d28d12":{
      "scriptId":"u3"},
    "858f8992ac2e472bbfe7478d4046de4f":{
      "scriptId":"u4"},
    "06732eec7dbd44ff8120eca7e5b1a964":{
      "scriptId":"u5"},
    "93bdeaac61f94de1bcd63ee1842389a0":{
      "scriptId":"u6"},
    "4b1f94daf6c741de88a2104a3b33deaa":{
      "scriptId":"u7"},
    "b1afe9f6a34d44c9844c1dbef7b34c0a":{
      "scriptId":"u8"},
    "196d9969498b4f29aa66f21ce7985681":{
      "scriptId":"u9"},
    "7aa7aa15525b4b06b1730ed011b36f81":{
      "scriptId":"u10"},
    "b3d6dcde1cb84c77b7d0142f0679c10c":{
      "scriptId":"u11"},
    "e66299265f464c258247ee6558c8b573":{
      "scriptId":"u12"}}});