$axure.loadCurrentPage({
  "url":"login.html",
  "generationDate":new Date(1459858380871.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0e574efe0e51476d8978098f60198f2e",
    "type":"Axure:Page",
    "name":"login",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"360b7512412d408585b1ced71b9b2dd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":178,
              "y":130},
            "size":{
              "width":383,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2155431ac4184fd4a453e094a7f601b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":178,
                  "y":130},
                "size":{
                  "width":383,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fc02b696f53492d816ac40c8752942d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":193},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"21981122123c4622b3c1aa1b3a553d5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":298,
              "y":155},
            "size":{
              "width":121,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c71749d8ba1a42cc921964f59b57b9f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":298,
                  "y":155},
                "size":{
                  "width":121,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43d8f9628f8d4693845d35aaa1b51167",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":466.999969482422,
              "y":190.5},
            "size":{
              "width":113,
              "height":30}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"1f4db64cd71f4629b3ceda317a98443c",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"13070a07f8b145de92982f05c392573b",
                  "label":"",
                  "parentDynamicPanel":"43d8f9628f8d4693845d35aaa1b51167",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":113,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"62d3e5ec686f4cb99f750be2df8cf412",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"43d8f9628f8d4693845d35aaa1b51167",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":113,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"Set value of OnLoadVariable equal to &quot;30&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetGlobalVariableValue",
                                    "arguments":[{
                                        "exprType":"globalVariableLiteral",
                                        "variableName":"OnLoadVariable"},
{
                                        "exprType":"stringLiteral",
                                        "value":"30",
                                        "stos":[]}]}]}},
{
                              "action":"setFunction",
                              "description":"Set text on countdown equal to &quot;[[OnLoadVariable]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetFormText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["b2ad28711f6940b2987908758d14569b"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"[[OnLoadVariable]]",
                                        "localVariables":{
},
                                        "stos":[{
                                            "sto":"var",
                                            "name":"onloadvariable"}]}]}]}},
{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to Next",
                              "panelsToStates":[{
                                  "panelPath":["43d8f9628f8d4693845d35aaa1b51167"],
                                  "stateInfo":{
                                    "setStateType":"next",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/login/u6.png"}}]},
{
              "id":"a5607438dad34ea3a251fcacb04f3113",
              "label":"State2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b2ad28711f6940b2987908758d14569b",
                  "label":"countdown",
                  "parentDynamicPanel":"43d8f9628f8d4693845d35aaa1b51167",
                  "type":"textBox",
                  "styleType":"textBox",
                  "disabled":true,
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "size":{
                      "width":80,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onTextChange":{
                      "description":"OnTextChange",
                      "cases":[{
                          "description":"Case 1<br> (If value of OnLoadVariable is greater than or equals &quot;2&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":">=",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"OnLoadVariable"}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"2",
                              "stos":[]}},
                          "actions":[{
                              "action":"wait",
                              "description":"Wait 1000 ms",
                              "waitTime":1000},
{
                              "action":"setFunction",
                              "description":"Set text on countdown equal to &quot;[[OnLoadVariable-1]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetFormText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["b2ad28711f6940b2987908758d14569b"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"[[OnLoadVariable-1]]",
                                        "localVariables":{
},
                                        "stos":[{
                                            "computedType":"int",
                                            "sto":"binOp",
                                            "op":"-",
                                            "leftSTO":{
                                              "sto":"var",
                                              "name":"onloadvariable"},
                                            "rightSTO":{
                                              "computedType":"int",
                                              "sto":"literal",
                                              "value":1}}]}]}]}},
{
                              "action":"setFunction",
                              "description":"Set value of OnLoadVariable equal to &quot;[[OnLoadVariable-1]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetGlobalVariableValue",
                                    "arguments":[{
                                        "exprType":"globalVariableLiteral",
                                        "variableName":"OnLoadVariable"},
{
                                        "exprType":"stringLiteral",
                                        "value":"[[OnLoadVariable-1]]",
                                        "localVariables":{
},
                                        "stos":[{
                                            "computedType":"int",
                                            "sto":"binOp",
                                            "op":"-",
                                            "leftSTO":{
                                              "sto":"var",
                                              "name":"onloadvariable"},
                                            "rightSTO":{
                                              "computedType":"int",
                                              "sto":"literal",
                                              "value":1}}]}]}]}}]},
{
                          "description":"Case 2<br> (Else If value of OnLoadVariable is less than or equals &quot;1&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"<=",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"OnLoadVariable"}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]}},
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set (Dynamic Panel) to Previous",
                              "panelsToStates":[{
                                  "panelPath":["43d8f9628f8d4693845d35aaa1b51167"],
                                  "stateInfo":{
                                    "setStateType":"previous",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"setFunction",
                              "description":"Set text on countdown equal to &quot;x&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetFormText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["b2ad28711f6940b2987908758d14569b"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"x",
                                        "stos":[]}]}]}}]}]}}}]}]},
{
          "id":"09041736d6a743daa5271901fc339f78",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":256},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d30ec8bbf0be4800ae1347308c8c1efd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":256},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open update in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"update.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"21048091a088469c974ff952f8659ac0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":253,
              "y":227},
            "size":{
              "width":142,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"863a0b7039c1496fab451cd0ca4a4287",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":253,
                  "y":227},
                "size":{
                  "width":142,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "360b7512412d408585b1ced71b9b2dd8":{
      "scriptId":"u0"},
    "2155431ac4184fd4a453e094a7f601b8":{
      "scriptId":"u1"},
    "5fc02b696f53492d816ac40c8752942d":{
      "scriptId":"u2"},
    "21981122123c4622b3c1aa1b3a553d5e":{
      "scriptId":"u3"},
    "c71749d8ba1a42cc921964f59b57b9f1":{
      "scriptId":"u4"},
    "43d8f9628f8d4693845d35aaa1b51167":{
      "scriptId":"u5"},
    "13070a07f8b145de92982f05c392573b":{
      "scriptId":"u6"},
    "62d3e5ec686f4cb99f750be2df8cf412":{
      "scriptId":"u7"},
    "b2ad28711f6940b2987908758d14569b":{
      "scriptId":"u8"},
    "09041736d6a743daa5271901fc339f78":{
      "scriptId":"u9"},
    "d30ec8bbf0be4800ae1347308c8c1efd":{
      "scriptId":"u10"},
    "21048091a088469c974ff952f8659ac0":{
      "scriptId":"u11"},
    "863a0b7039c1496fab451cd0ca4a4287":{
      "scriptId":"u12"}}});