$axure.loadCurrentPage({
  "url":"cable-setting.html",
  "generationDate":new Date(1459858381338.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d05e522516ee4f8883f34d3c41e37412",
    "type":"Axure:Page",
    "name":"Cable-setting",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a8dac9c683bb418ba2c45635584de838",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":327},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d09f48e79ba2483393c2b97578215cb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":327},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"9dd2d97ee5444d60988392cb9bf2c933",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":47},
            "size":{
              "width":27,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3635fabffda46be860fafde77311a5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":47},
                "size":{
                  "width":27,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b83284b84e2e4b3c81bf994d82023730",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":47},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cda0e8cd20954a46af06841008e9f04e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408,
                  "y":47},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"ca609808cd324a66928c443f92d3aa0c",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":87},
            "size":{
              "width":170,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb6dff99c88645dab821f7af7b11d057",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":87},
                "size":{
                  "width":170,
                  "height":15}},
              "adaptiveStyles":{
}}]},
{
          "id":"ac98f8468885498f876ac797beda9dcf",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":112},
            "size":{
              "width":170,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"894228753af443af88f04164593ca859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":112},
                "size":{
                  "width":170,
                  "height":15}},
              "adaptiveStyles":{
}}]},
{
          "id":"c21773c4a0ce4017a983e2064396ac12",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":140},
            "size":{
              "width":330,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43130b0dd98148f2960135ecff2c3249",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cc28d19e73444873af9abd6e4cabb8c5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u10.png"}},
{
              "id":"d4cc51fb9b804fe78b3ce51b4b67c038",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"91869fa06da1449caf587537fa51b867",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u10.png"}},
{
              "id":"317fd8118a9f4405982b844d4b304e2a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dfc5f053d871478fa5bcdcddfbd71d01",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u10.png"}},
{
              "id":"a8bd429ae1de4f51896cb5c40f9cc2d0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":0},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b08b23cfe36d4eda8ef5ba43c50e64ad",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":0},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u12.png"}},
{
              "id":"ddf38fe6ca8b49f4b863e8889c6c832a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":30},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8d74683713ed432396cf4518608f56d6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":30},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u12.png"}},
{
              "id":"e2f6bc3cb323470ea384224cd1f3683f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":60},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"11f78921baed4fc692c6bbdbb4f3b8f5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":60},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u12.png"}},
{
              "id":"e22c666ff2bb4b3093ebe0c7da44c75b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"61c38e7ed3ac40dca3c936079c9c1826",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u10.png"}},
{
              "id":"2d91366cf08b46a18bf6076f9b61f506",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":90},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6fa4a4ccae2c4956b61eadc684aa85bf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":90},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u12.png"}},
{
              "id":"120cb563f350433b80f376291efe659f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6ebdba453372486ab8609845b171aa82",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u10.png"}},
{
              "id":"2e8d15ef90d943499ba9e8736fad6574",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":120},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f6e34824cd0f4c34873cf8294cd82a66",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":120},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u12.png"}},
{
              "id":"dc9cc34a389c4b9598e5588e25890524",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"74815b4077f9453c90c4c3e93c56e4a2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u30.png"}},
{
              "id":"dc4bf57809b3475d9dc8da94650327bb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":150},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"329ded148c244276aff132a6878d737d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":150},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u32.png"}}]},
{
          "id":"e10aef6f5b07477c8ac258713c08430a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":11},
            "size":{
              "width":156,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9e57fb0ce9f4337b385d5ef3023f2e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":11},
                "size":{
                  "width":156,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f955be9bab4438eb0cae08b6943da4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":326},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60c39d5e79f944b397e9c395dc71247a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":326},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"b03f6121f5d041e688a1a59cd530c917",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":131,
              "y":66},
            "size":{
              "width":144,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b326bb6107b42d691612bd1d6f1a7c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":131,
                  "y":66},
                "size":{
                  "width":144,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a8dac9c683bb418ba2c45635584de838":{
      "scriptId":"u0"},
    "d09f48e79ba2483393c2b97578215cb2":{
      "scriptId":"u1"},
    "9dd2d97ee5444d60988392cb9bf2c933":{
      "scriptId":"u2"},
    "c3635fabffda46be860fafde77311a5e":{
      "scriptId":"u3"},
    "b83284b84e2e4b3c81bf994d82023730":{
      "scriptId":"u4"},
    "cda0e8cd20954a46af06841008e9f04e":{
      "scriptId":"u5"},
    "ca609808cd324a66928c443f92d3aa0c":{
      "scriptId":"u6"},
    "eb6dff99c88645dab821f7af7b11d057":{
      "scriptId":"u7"},
    "ac98f8468885498f876ac797beda9dcf":{
      "scriptId":"u8"},
    "894228753af443af88f04164593ca859":{
      "scriptId":"u9"},
    "c21773c4a0ce4017a983e2064396ac12":{
      "scriptId":"u10"},
    "43130b0dd98148f2960135ecff2c3249":{
      "scriptId":"u11"},
    "cc28d19e73444873af9abd6e4cabb8c5":{
      "scriptId":"u12"},
    "a8bd429ae1de4f51896cb5c40f9cc2d0":{
      "scriptId":"u13"},
    "b08b23cfe36d4eda8ef5ba43c50e64ad":{
      "scriptId":"u14"},
    "d4cc51fb9b804fe78b3ce51b4b67c038":{
      "scriptId":"u15"},
    "91869fa06da1449caf587537fa51b867":{
      "scriptId":"u16"},
    "ddf38fe6ca8b49f4b863e8889c6c832a":{
      "scriptId":"u17"},
    "8d74683713ed432396cf4518608f56d6":{
      "scriptId":"u18"},
    "317fd8118a9f4405982b844d4b304e2a":{
      "scriptId":"u19"},
    "dfc5f053d871478fa5bcdcddfbd71d01":{
      "scriptId":"u20"},
    "e2f6bc3cb323470ea384224cd1f3683f":{
      "scriptId":"u21"},
    "11f78921baed4fc692c6bbdbb4f3b8f5":{
      "scriptId":"u22"},
    "e22c666ff2bb4b3093ebe0c7da44c75b":{
      "scriptId":"u23"},
    "61c38e7ed3ac40dca3c936079c9c1826":{
      "scriptId":"u24"},
    "2d91366cf08b46a18bf6076f9b61f506":{
      "scriptId":"u25"},
    "6fa4a4ccae2c4956b61eadc684aa85bf":{
      "scriptId":"u26"},
    "120cb563f350433b80f376291efe659f":{
      "scriptId":"u27"},
    "6ebdba453372486ab8609845b171aa82":{
      "scriptId":"u28"},
    "2e8d15ef90d943499ba9e8736fad6574":{
      "scriptId":"u29"},
    "f6e34824cd0f4c34873cf8294cd82a66":{
      "scriptId":"u30"},
    "dc9cc34a389c4b9598e5588e25890524":{
      "scriptId":"u31"},
    "74815b4077f9453c90c4c3e93c56e4a2":{
      "scriptId":"u32"},
    "dc4bf57809b3475d9dc8da94650327bb":{
      "scriptId":"u33"},
    "329ded148c244276aff132a6878d737d":{
      "scriptId":"u34"},
    "e10aef6f5b07477c8ac258713c08430a":{
      "scriptId":"u35"},
    "b9e57fb0ce9f4337b385d5ef3023f2e7":{
      "scriptId":"u36"},
    "7f955be9bab4438eb0cae08b6943da4f":{
      "scriptId":"u37"},
    "60c39d5e79f944b397e9c395dc71247a":{
      "scriptId":"u38"},
    "b03f6121f5d041e688a1a59cd530c917":{
      "scriptId":"u39"},
    "6b326bb6107b42d691612bd1d6f1a7c9":{
      "scriptId":"u40"}}});