$axure.loadCurrentPage({
  "url":"wifi-hide-detail-setting.html",
  "generationDate":new Date(1459858381285.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ce53a35c0df44b8b9cc38a5eb5095c2f",
    "type":"Axure:Page",
    "name":"Wifi-hide-detail-setting",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a8dac9c683bb418ba2c45635584de838",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":175},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d09f48e79ba2483393c2b97578215cb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":175},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"6f439e26c0ad4d4b9e3e929af818d0cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":40},
            "size":{
              "width":27,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a6f43bc8efc4314a368e5bd17719859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":40},
                "size":{
                  "width":27,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"858f8992ac2e472bbfe7478d4046de4f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":65},
            "size":{
              "width":330,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06732eec7dbd44ff8120eca7e5b1a964",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"93bdeaac61f94de1bcd63ee1842389a0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u10.png"}},
{
              "id":"3d32efb46e414a5e803f691eec773fc3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bb965c178683419ca2240d022e14a4d9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u10.png"}},
{
              "id":"64bd1c8a43514a47a784ef239bc41da8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":104,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1bcbaca7b6dd4515b0e832b32aa2d58c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":104,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u30.png"}},
{
              "id":"4b1f94daf6c741de88a2104a3b33deaa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":0},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1afe9f6a34d44c9844c1dbef7b34c0a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":0},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u12.png"}},
{
              "id":"cb9fb1748ef5415087396fa5ea63d8b4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":30},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c3f973fefb614b95a01c4ac0cf76ba78",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":30},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u12.png"}},
{
              "id":"88c07188026c4c6398d33a2661219c36",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":104,
                  "y":60},
                "size":{
                  "width":226,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7d5e2c1c0b9044bca9cd3bb43278f3bd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":104,
                      "y":60},
                    "size":{
                      "width":226,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/wifi-detail-setting/u32.png"}}]},
{
          "id":"37700cd408c94176bfbeb8652bdfd8b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":11},
            "size":{
              "width":168,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef0dcf04eba469da46bf2899c7f8f60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":11},
                "size":{
                  "width":168,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5148cfd2063e4bf897fc8711c962912c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":361,
              "y":175},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e74efc469b14d50924fe84b99bdcd71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":361,
                  "y":175},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Back in Current Window",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/login/u9.png"}},
{
          "id":"bc045549da294d9b8e5727afb69c9c56",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":249,
              "y":99},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "a8dac9c683bb418ba2c45635584de838":{
      "scriptId":"u0"},
    "d09f48e79ba2483393c2b97578215cb2":{
      "scriptId":"u1"},
    "6f439e26c0ad4d4b9e3e929af818d0cf":{
      "scriptId":"u2"},
    "1a6f43bc8efc4314a368e5bd17719859":{
      "scriptId":"u3"},
    "858f8992ac2e472bbfe7478d4046de4f":{
      "scriptId":"u4"},
    "06732eec7dbd44ff8120eca7e5b1a964":{
      "scriptId":"u5"},
    "93bdeaac61f94de1bcd63ee1842389a0":{
      "scriptId":"u6"},
    "4b1f94daf6c741de88a2104a3b33deaa":{
      "scriptId":"u7"},
    "b1afe9f6a34d44c9844c1dbef7b34c0a":{
      "scriptId":"u8"},
    "3d32efb46e414a5e803f691eec773fc3":{
      "scriptId":"u9"},
    "bb965c178683419ca2240d022e14a4d9":{
      "scriptId":"u10"},
    "cb9fb1748ef5415087396fa5ea63d8b4":{
      "scriptId":"u11"},
    "c3f973fefb614b95a01c4ac0cf76ba78":{
      "scriptId":"u12"},
    "64bd1c8a43514a47a784ef239bc41da8":{
      "scriptId":"u13"},
    "1bcbaca7b6dd4515b0e832b32aa2d58c":{
      "scriptId":"u14"},
    "88c07188026c4c6398d33a2661219c36":{
      "scriptId":"u15"},
    "7d5e2c1c0b9044bca9cd3bb43278f3bd":{
      "scriptId":"u16"},
    "37700cd408c94176bfbeb8652bdfd8b2":{
      "scriptId":"u17"},
    "8ef0dcf04eba469da46bf2899c7f8f60":{
      "scriptId":"u18"},
    "5148cfd2063e4bf897fc8711c962912c":{
      "scriptId":"u19"},
    "9e74efc469b14d50924fe84b99bdcd71":{
      "scriptId":"u20"},
    "bc045549da294d9b8e5727afb69c9c56":{
      "scriptId":"u21"}}});